### ISSUE TITLE
npm install getting failed

### ISSUE THREAD

**Issue by imarungupta** [johnpapa/lite-server#137]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.6.0
3 info using node@v10.2.1
4 verbose npm-session 89e93d34ef14adf2
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall angular-quickstart@1.0.0
7 info lifecycle angular-quickstart@1.0.0~preinstall: angular-quickstart@1.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 silly fetchPackageMetaData error for lite-server@^2.2.2 request to https://registry.npmjs.org/lite-server failed, reason: self signed certificate in certificate chain
15 silly fetchPackageMetaData error for typescript@~2.1.0 request to https://registry.npmjs.org/typescript failed, reason: self signed certificate in certificate chain
16 silly fetchPackageMetaData error for karma-cli@^1.0.1 request to https://registry.npmjs.org/karma-cli failed, reason: self signed certificate in certificate chain
17 silly fetchPackageMetaData error for canonical-path@0.0.2 request to https://registry.npmjs.org/canonical-path failed, reason: self signed certificate in certificate chain
18 silly fetchPackageMetaData error for lodash@^4.16.4 request to https://registry.npmjs.org/lodash failed, reason: self signed certificate in certificate chain
19 silly fetchPackageMetaData error for karma-chrome-launcher@^2.0.0 request to https://registry.npmjs.org/karma-chrome-launcher failed, reason: self signed certificate in certificate chain
20 silly fetchPackageMetaData error for jasmine-core@~2.4.1 request to https://registry.npmjs.org/jasmine-core failed, reason: self signed certificate in certificate chain
21 silly fetchPackageMetaData error for tslint@^3.15.1 request to https://registry.npmjs.org/tslint failed, reason: self signed certificate in certificate chain
22 silly fetchPackageMetaData error for concurrently@^3.2.0 request to https://registry.npmjs.org/concurrently failed, reason: self signed certificate in certificate chain
23 silly fetchPackageMetaData error for karma@^1.3.0 request to https://registry.npmjs.org/karma failed, reason: self signed certificate in certificate chain
24 silly fetchPackageMetaData error for karma-jasmine@^1.0.2 request to https://registry.npmjs.org/karma-jasmine failed, reason: self signed certificate in certificate chain
25 silly fetchPackageMetaData error for karma-jasmine-html-reporter@^0.2.2 request to https://registry.npmjs.org/karma-jasmine-html-reporter failed, reason: self signed certificate in certificate chain
26 silly fetchPackageMetaData error for protractor@~4.0.14 request to https://registry.npmjs.org/protractor failed, reason: self signed certificate in certificate chain
27 silly fetchPackageMetaData error for rimraf@^2.5.4 request to https://registry.npmjs.org/rimraf failed, reason: self signed certificate in certificate chain
28 silly fetchPackageMetaData error for @angular/compiler@~4.3.4 request to https://registry.npmjs.org/@angular%2fcompiler failed, reason: self signed certificate in certificate chain
29 silly fetchPackageMetaData error for @angular/forms@~4.3.4 request to https://registry.npmjs.org/@angular%2fforms failed, reason: self signed certificate in certificate chain
30 silly fetchPackageMetaData error for @types/jasmine@2.5.36 request to https://registry.npmjs.org/@types%2fjasmine failed, reason: self signed certificate in certificate chain
31 silly fetchPackageMetaData error for @types/node@^6.0.46 request to https://registry.npmjs.org/@types%2fnode failed, reason: self signed certificate in certificate chain
32 silly fetchPackageMetaData error for @angular/common@~4.3.4 request to https://registry.npmjs.org/@angular%2fcommon failed, reason: self signed certificate in certificate chain
33 silly fetchPackageMetaData error for @angular/core@~4.3.4 request to https://registry.npmjs.org/@angular%2fcore failed, reason: self signed certificate in certificate chain
34 silly fetchPackageMetaData error for @angular/http@~4.3.4 request to https://registry.npmjs.org/@angular%2fhttp failed, reason: self signed certificate in certificate chain
35 silly fetchPackageMetaData error for @angular/platform-browser@~4.3.4 request to https://registry.npmjs.org/@angular%2fplatform-browser failed, reason: self signed certificate in certificate chain
36 silly fetchPackageMetaData error for @angular/platform-browser-dynamic@~4.3.4 request to https://registry.npmjs.org/@angular%2fplatform-browser-dynamic failed, reason: self signed certificate in certificate chain
37 silly fetchPackageMetaData error for rxjs@5.0.1 request to https://registry.npmjs.org/rxjs failed, reason: self signed certificate in certificate chain
38 silly fetchPackageMetaData error for systemjs@0.19.40 request to https://registry.npmjs.org/systemjs failed, reason: self signed certificate in certificate chain
39 silly fetchPackageMetaData error for zone.js@^0.8.4 request to https://registry.npmjs.org/zone.js failed, reason: self signed certificate in certificate chain
40 silly fetchPackageMetaData error for core-js@^2.4.1 request to https://registry.npmjs.org/core-js failed, reason: self signed certificate in certificate chain
41 silly fetchPackageMetaData error for @angular/router@~4.3.4 request to https://registry.npmjs.org/@angular%2frouter failed, reason: self signed certificate in certificate chain
42 silly fetchPackageMetaData error for angular-in-memory-web-api@~0.3.0 request to https://registry.npmjs.org/angular-in-memory-web-api failed, reason: self signed certificate in certificate chain
43 silly fetchPackageMetaData error for @angular/common@~4.3.4 request to https://registry.npmjs.org/@angular%2fcommon failed, reason: self signed certificate in certificate chain
44 silly fetchPackageMetaData error for @angular/core@~4.3.4 request to https://registry.npmjs.org/@angular%2fcore failed, reason: self signed certificate in certificate chain
45 silly fetchPackageMetaData error for @angular/compiler@~4.3.4 request to https://registry.npmjs.org/@angular%2fcompiler failed, reason: self signed certificate in certificate chain
46 silly fetchPackageMetaData error for systemjs@0.19.40 request to https://registry.npmjs.org/systemjs failed, reason: self signed certificate in certificate chain
47 silly fetchPackageMetaData error for angular-in-memory-web-api@~0.3.0 request to https://registry.npmjs.org/angular-in-memory-web-api failed, reason: self signed certificate in certificate chain
48 silly fetchPackageMetaData error for @angular/forms@~4.3.4 request to https://registry.npmjs.org/@angular%2fforms failed, reason: self signed certificate in certificate chain
49 silly fetchPackageMetaData error for @angular/router@~4.3.4 request to https://registry.npmjs.org/@angular%2frouter failed, reason: self signed certificate in certificate chain
50 silly fetchPackageMetaData error for @angular/platform-browser-dynamic@~4.3.4 request to https://registry.npmjs.org/@angular%2fplatform-browser-dynamic failed, reason: self signed certificate in certificate chain
51 silly fetchPackageMetaData error for @angular/platform-browser@~4.3.4 request to https://registry.npmjs.org/@angular%2fplatform-browser failed, reason: self signed certificate in certificate chain
52 silly fetchPackageMetaData error for @angular/http@~4.3.4 request to https://registry.npmjs.org/@angular%2fhttp failed, reason: self signed certificate in certificate chain
53 silly fetchPackageMetaData error for rxjs@5.0.1 request to https://registry.npmjs.org/rxjs failed, reason: self signed certificate in certificate chain
54 silly fetchPackageMetaData error for zone.js@^0.8.4 request to https://registry.npmjs.org/zone.js failed, reason: self signed certificate in certificate chain
55 silly fetchPackageMetaData error for core-js@^2.4.1 request to https://registry.npmjs.org/core-js failed, reason: self signed certificate in certificate chain
56 silly saveTree angular-quickstart@1.0.0
57 verbose type system
58 verbose stack FetchError: request to https://registry.npmjs.org/@angular%2fcommon failed, reason: self signed certificate in certificate chain
58 verbose stack     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
58 verbose stack     at ClientRequest.emit (events.js:182:13)
58 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:382:9)
58 verbose stack     at TLSSocket.emit (events.js:182:13)
58 verbose stack     at emitErrorNT (internal/streams/destroy.js:82:8)
58 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
58 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
59 verbose cwd D:\Users\agupta.PSCU\Downloads\quickstart-master\quickstart-master
60 verbose Windows_NT 6.1.7601
61 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
62 verbose node v10.2.1
63 verbose npm  v5.6.0
64 error code SELF_SIGNED_CERT_IN_CHAIN
65 error errno SELF_SIGNED_CERT_IN_CHAIN
66 error request to https://registry.npmjs.org/@angular%2fcommon failed, reason: self signed certificate in certificate chain
67 verbose exit [ 1, true ]

**Comment by sammypearl** [comment]
i faced something like this while installing typescript, all i did was to set strict ssl to false by using this code 
"npm config set strict-ssl false". i hope it help you as well.
