### ISSUE TITLE
 throw (err);

### ISSUE THREAD

**Issue by Viv-Galinari** [johnpapa/lite-server#142]
Before you open an issue, please check if a similar issue already exists or has been closed before.

### A descriptive title
The behavior you expect to see, and the actual behavior...

For feature requests, a description of the problem you're trying to solve, including *why* you think this is a problem.

### Bug repro steps
Please give us an isolated way to reproduce the behavior (example: GitHub repository with code that anyone can clone to observe the problem, or a Dockerfile that replicates your environment):

1.
2.
3.

### Environment
- `lite-server` version:
- `nodejs` version:
- `npm` version:
- OS type/version:

**Comment by Viv-Galinari** [comment]
Hello, I've been experiencing issues starting lite-server  v2.3.0 and would love if I could get any help. I get this error message
/usr/local/lib/node_modules/lite-server/lib/lite-server.js:33
      throw (err);  

SyntaxError: /Users/viviangalinari/Desktop/newcopy/mercado/bs-config.json: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:671:27)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at start (/usr/local/lib/node_modules/lite-server/lib/lite-server.js:28:17)

bs-config.json
> {
  "port": 8005,
  "server": ["app", ".", "build"]
}

Can you please advice? Many thanks
