### ISSUE TITLE
Crashes When Trying To Load Angular2 5min Tutorial Code 

### ISSUE THREAD

**Issue by tyshkev** [johnpapa/lite-server#35]
I couldn't make it work with angular code using both local and global installation, via npm and by calling it directly.

The execution always stops on unhandled exception:

'''
events.js:154
       throw er; // Unhandled 'error' event
       ^ 
Error: watch node_modules/insight/node_modules/lodash/internal/LodashWrapper.js ENOSPC
  at exports._errnoException (util.js:856:11)at FSWatcher.start (fs.js:1313:19)
  at Object.fs.watch (fs.js:1341:11)at createFsWatchInstance (/node_modules/chokidar/lib/nodefs-handler.js:37:15)
  at setFsWatchListener (/node_modules/chokidar/lib/nodefs-handler.js:80:15)
  at FSWatcher.NodeFsHandler._watchWithNodeFs (/node_modules/chokidar/lib/nodefs-handler.js:228:14)
  at FSWatcher.NodeFsHandler._handleFile (/node_modules/chokidar/lib/nodefs-handler.js:255:21)
  at FSWatcher.<anonymous> (/node_modules/chokidar/lib/nodefs-handler.js:473:21)
  at FSReqWrap.oncomplete (fs.js:82:15)
'''

**npm-debug.log:**

[0] info it worked if it ends with ok
[1] verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'lite' ]
[2] info using npm@3.6.0
[3] info using node@v5.6.0
[4] verbose run-script [ 'prelite', 'lite', 'postlite' ]
[5] info lifecycle angular2-quickstart@1.0.0~prelite: angular2-quickstart@1.0.0
[6] silly lifecycle angular2-quickstart@1.0.0~prelite: no script for prelite, continuing
[7] info lifecycle angular2-quickstart@1.0.0~lite: angular2-quickstart@1.0.0
[8] verbose lifecycle angular2-quickstart@1.0.0~lite: unsafe-perm in lifecycle true
[11] silly lifecycle angular2-quickstart@1.0.0~lite: Args: [ '-c', 'lite-server' ]
[12] silly lifecycle angular2-quickstart@1.0.0~lite: Returned: code: 1  signal: null
[13] info lifecycle angular2-quickstart@1.0.0~lite: Failed to exec lite script
[14] verbose stack Error: angular2-quickstart@1.0.0 lite: `lite-server`
[15] verbose stack Exit status 1
[16] verbose stack at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
[17] verbose stack at emitTwo (events.js: 100:13)
[18] verbose stack at EventEmitter.emit (events.js:185:7)
[19] verbose stack at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
[20] verbose stack at emitTwo (events.js: 100:13)
[21] verbose stack at ChildProcess.emit (events.js:185:7)
[22] verbose stack at maybeClose (internal/child_process.js:827:16)
[23] verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[24] verbose pkgid angular2-quickstart@1.0.0
[25] verbose cwd /home/tyshkev/code/study/angular/quickstart
[26] error Linux 3.19.0-49-generic
[27] error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "lite"
[28] error node v5.6.0
[29] error npm  v3.6.0
[30] error code ELIFECYCLE
[31] error angular2-quickstart@1.0.0 lite: `lite-server`
[32] error Exit status 1
 ...
[33] verbose exit [ 1, true ]

This doesn't happen when angular is not included on the page. 
Same package configuration with browser-sync v2.11.1 has no issues.

**Comment by dzwicker** [comment]
Here was the same. I am on ubuntu and the workaround mentioned in BrowserSync/browser-sync#224 by @amoswachanga  
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

**Comment by hoelter** [comment]
I had the same problem on Linux 4.1.18-1-1-Manjaro. The above command fixed it for me.

**Comment by tyshkev** [comment]
Thank you @dzwicker.

**Comment by ivanzvakoms** [comment]
How do I set this up on OSX?
