### ISSUE TITLE
Unable to run lite-server on "Windows Subsystem for Linux"

### ISSUE THREAD

**Issue by jan-valek** [johnpapa/lite-server#95]
### Unable to run lite-server on "Windows Subsystem for Linux"

if I try run my app hosted on your server I get this output listed below. On other platforms (Windows 10,Mac OS X) is running correctly.

 lite-server -c bs-config.json

/mnt/c/Work/Code/Private/canvas/node_modules/dev-ip/lib/dev-ip.js:21
    var networkInterfaces = require("os").networkInterfaces();
                                          ^

Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at getIp (/mnt/c/Work/Code/Private/canvas/node_modules/dev-ip/lib/dev-ip.js:21:43)
    at Object.<anonymous> (/mnt/c/Work/Code/Private/canvas/node_modules/browser-sync/lib/utils.js:4:38)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)

npm ERR! Linux 3.4.0+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! seed@1.0.0 start: `lite-server -c bs-config.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the seed@1.0.0 start script 'lite-server -c bs-config.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lite-server -c bs-config.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Work/Code/Private/canvas/npm-debug.log
The behavior you expect to see, and the actual behavior...
### Bug repro steps

I have project based on this git repository:
https://github.com/brut4r/masap
I run npm install and npm install bower -g
and next npm start
### Environment
- `lite-server` version: lite-server@2.2.2
- `nodejs` version: v6.3.1
- `npm` version: 3.10.3
- OS type/version: windows 10 1607, windows subsystem for linux

**Comment by vanntian** [comment]
I have the same issue。

**Comment by orenmizr** [comment]
+1 i have the same issue

**Comment by Chris2011** [comment]
exact the same problem.

**Comment by tuomastielinen** [comment]
I also have the same issue when i try to run code from this repo: https://github.com/DeborahK/Angular2-GettingStarted.

```bash
tuomas@yoga-900:/mnt/c/Users/Tuomas/Desktop/projektit/Angular2-GettingStarted/APM$ npm start

> product-management@1.0.0 start /mnt/c/Users/Tuomas/Desktop/projektit/Angular2-GettingStarted/APM
> tsc && concurrently "tsc -w" "lite-server"

[1] /mnt/c/Users/Tuomas/Desktop/projektit/Angular2-GettingStarted/APM/node_modules/dev-ip/lib/dev-ip.js:21
[1]     var networkInterfaces = require("os").networkInterfaces();
[1]                                           ^
[1]
[1] Error: ENOTSUP: operation not supported on socket, uv_interface_addresses
[1]     at getIp (/mnt/c/Users/Tuomas/Desktop/projektit/Angular2-GettingStarted/APM/node_modules/dev-ip/lib/dev-ip.js:21
:43)
[1]     at Object.<anonymous> (/mnt/c/Users/Tuomas/Desktop/projektit/Angular2-GettingStarted/APM/node_modules/browser-sy
nc/lib/utils.js:4:38)
[1]     at Module._compile (module.js:573:32)
[1]     at Object.Module._extensions..js (module.js:582:10)
[1]     at Module.load (module.js:490:32)
[1]     at tryModuleLoad (module.js:449:12)
[1]     at Function.Module._load (module.js:441:3)
[1]     at Module.require (module.js:500:17)
[1]     at require (internal/module.js:20:19)
[1]     at Object.<anonymous> (/mnt/c/Users/Tuomas/Desktop/projektit/Angular2-GettingStarted/APM/node_modules/browser-sy
nc/lib/snippet.js:9:20)
[1] lite-server exited with code 1
[0] 9:42:45 PM - Compilation complete. Watching for file changes.
```

**Comment by tuomastielinen** [comment]
The fix is coming soon, if these problems are related.

https://github.com/Microsoft/BashOnWindows/issues/468#issuecomment-256983706
