### ISSUE TITLE
Issue with npm start

### ISSUE THREAD

**Issue by feeleen** [johnpapa/lite-server#98]
https://github.com/angular/quickstart/issues/139

**Comment by feeleen** [comment]
**Error: spawn cmd ENOENT
at exports._errnoException (util.js:893:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32

 at onErrorNT (internal/child_process.js:348:16)
 at _combinedTickCallback (internal/process/next_tick.js:74:11)
 at process._tickCallback (internal/process/next_tick.js:98:9)
npm
ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\node
\node_modules\npm\bin\npm-cli.js" "run" "lite"
npm ERR! node v5.11.1
npm
ERR! npm v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! angular2-quickstart@1.0.0 lite: lite-server
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-quickstart@1.0.0 lite script 'lite-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

npm ERR! If you do, this is most likely a problem with the angular2-quicksta
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! lite-server
npm ERR!
You can get information on how to open an issue for this project with:
npm ERR! npm bugs angular2-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls angular2-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! C:\BackUp\projects\projects\Angular2.0\angular2-quickstart\npm-
ug.log
